// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Revalidate;

#nullable disable

namespace Revalidate.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250921202717_IncreaseExeVersion")]
    partial class IncreaseExeVersion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Revalidate.Entities.FileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("mediumblob");

                    b.Property<string>("Etag")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("Revalidate.Entities.GhostCheckpointEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("GhostId")
                        .HasColumnType("char(36)");

                    b.Property<float?>("Speed")
                        .HasColumnType("float");

                    b.Property<int?>("StuntsScore")
                        .HasColumnType("int");

                    b.Property<int?>("Time")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GhostId");

                    b.ToTable("GhostCheckpoints");
                });

            modelBuilder.Entity("Revalidate.Entities.GhostInputEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)");

                    b.Property<bool?>("Pressed")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Time")
                        .HasColumnType("int");

                    b.Property<Guid>("ValidationResultId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("Value")
                        .HasColumnType("int");

                    b.Property<float?>("ValueF")
                        .HasColumnType("float");

                    b.Property<ushort?>("X")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("Y")
                        .HasColumnType("smallint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("ValidationResultId");

                    b.ToTable("GhostInputs");
                });

            modelBuilder.Entity("Revalidate.Entities.MapEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int?>("AuthorScore")
                        .HasColumnType("int");

                    b.Property<int?>("AuthorTime")
                        .HasColumnType("int");

                    b.Property<string>("DeformattedName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EnvironmentId")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<Guid>("FileId")
                        .HasColumnType("char(36)");

                    b.Property<int>("GameVersion")
                        .HasColumnType("int");

                    b.Property<Guid?>("MapId")
                        .HasColumnType("char(36)");

                    b.Property<string>("MapUid")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("ModeId")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("NbLaps")
                        .HasColumnType("int");

                    b.Property<byte[]>("Sha256")
                        .HasColumnType("BINARY(32)");

                    b.Property<byte[]>("Thumbnail")
                        .HasColumnType("mediumblob");

                    b.Property<bool>("UserUploaded")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.HasIndex("MapUid");

                    b.HasIndex("Sha256")
                        .IsUnique();

                    b.ToTable("Maps");
                });

            modelBuilder.Entity("Revalidate.Entities.ValidationClientResultEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("ValidationClientResultEntity");
                });

            modelBuilder.Entity("Revalidate.Entities.ValidationDistroResultEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DeclaredNbCheckpoints")
                        .HasColumnType("int");

                    b.Property<int?>("DeclaredNbRespawns")
                        .HasColumnType("int");

                    b.Property<int?>("DeclaredScore")
                        .HasColumnType("int");

                    b.Property<int?>("DeclaredTime")
                        .HasColumnType("int");

                    b.Property<string>("Desc")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DistroId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("InputsResult")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<bool?>("IsValid")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsValidExtracted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("LogId")
                        .HasColumnType("int");

                    b.Property<string>("RawJsonResult")
                        .HasMaxLength(32767)
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ResultId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("ValidatedNbCheckpoints")
                        .HasColumnType("int");

                    b.Property<int?>("ValidatedNbRespawns")
                        .HasColumnType("int");

                    b.Property<int?>("ValidatedScore")
                        .HasColumnType("int");

                    b.Property<int?>("ValidatedTime")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LogId");

                    b.HasIndex("ResultId");

                    b.ToTable("ValidationDistroResults");
                });

            modelBuilder.Entity("Revalidate.Entities.ValidationLogEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Log")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ValidationLogs");
                });

            modelBuilder.Entity("Revalidate.Entities.ValidationRequestEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Warnings")
                        .IsRequired()
                        .HasColumnType("JSON");

                    b.HasKey("Id");

                    b.ToTable("ValidationRequests");
                });

            modelBuilder.Entity("Revalidate.Entities.ValidationResultEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("CpuKind")
                        .HasColumnType("int");

                    b.Property<int>("EventsDuration")
                        .HasColumnType("int");

                    b.Property<uint>("ExeChecksum")
                        .HasColumnType("int unsigned");

                    b.Property<string>("ExeVersion")
                        .HasMaxLength(32767)
                        .HasColumnType("longtext");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("GameVersion")
                        .HasColumnType("int");

                    b.Property<Guid?>("GhostId")
                        .HasColumnType("char(36)");

                    b.Property<string>("GhostUid")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsGhostExtracted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsValid")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsValidExtracted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Login")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid?>("MapId")
                        .HasColumnType("char(36)");

                    b.Property<string>("MapUid")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("NbInputs")
                        .HasColumnType("int");

                    b.Property<int>("OsKind")
                        .HasColumnType("int");

                    b.Property<string>("Problems")
                        .IsRequired()
                        .HasColumnType("JSON");

                    b.Property<string>("RaceSettings")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("RaceTime")
                        .HasColumnType("int");

                    b.Property<Guid?>("ReplayId")
                        .HasColumnType("char(36)");

                    b.Property<int>("ServerHostType")
                        .HasColumnType("int");

                    b.Property<string>("ServerVersion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<byte[]>("Sha256")
                        .IsRequired()
                        .HasColumnType("BINARY(32)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("SteeringWheelSensitivity")
                        .HasColumnType("tinyint(1)");

                    b.Property<byte[]>("TitleChecksum")
                        .HasColumnType("BINARY(32)");

                    b.Property<string>("TitleId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Url")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("ValidationSeed")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("WalltimeEndedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("WalltimeStartedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("GhostId");

                    b.HasIndex("MapId");

                    b.HasIndex("ReplayId");

                    b.HasIndex("Sha256");

                    b.ToTable("ValidationResults");
                });

            modelBuilder.Entity("ValidationRequestEntityValidationResultEntity", b =>
                {
                    b.Property<Guid>("RequestsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ResultsId")
                        .HasColumnType("char(36)");

                    b.HasKey("RequestsId", "ResultsId");

                    b.HasIndex("ResultsId");

                    b.ToTable("ValidationRequestEntityValidationResultEntity");
                });

            modelBuilder.Entity("Revalidate.Entities.GhostCheckpointEntity", b =>
                {
                    b.HasOne("Revalidate.Entities.ValidationResultEntity", "Ghost")
                        .WithMany("Checkpoints")
                        .HasForeignKey("GhostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ghost");
                });

            modelBuilder.Entity("Revalidate.Entities.GhostInputEntity", b =>
                {
                    b.HasOne("Revalidate.Entities.ValidationResultEntity", "ValidationResult")
                        .WithMany("Inputs")
                        .HasForeignKey("ValidationResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ValidationResult");
                });

            modelBuilder.Entity("Revalidate.Entities.MapEntity", b =>
                {
                    b.HasOne("Revalidate.Entities.FileEntity", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("Revalidate.Entities.ValidationDistroResultEntity", b =>
                {
                    b.HasOne("Revalidate.Entities.ValidationLogEntity", "Log")
                        .WithMany("Results")
                        .HasForeignKey("LogId");

                    b.HasOne("Revalidate.Entities.ValidationResultEntity", "Result")
                        .WithMany("Distros")
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Log");

                    b.Navigation("Result");
                });

            modelBuilder.Entity("Revalidate.Entities.ValidationResultEntity", b =>
                {
                    b.HasOne("Revalidate.Entities.ValidationClientResultEntity", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId");

                    b.HasOne("Revalidate.Entities.FileEntity", "Ghost")
                        .WithMany()
                        .HasForeignKey("GhostId");

                    b.HasOne("Revalidate.Entities.MapEntity", "Map")
                        .WithMany()
                        .HasForeignKey("MapId");

                    b.HasOne("Revalidate.Entities.FileEntity", "Replay")
                        .WithMany()
                        .HasForeignKey("ReplayId");

                    b.Navigation("Client");

                    b.Navigation("Ghost");

                    b.Navigation("Map");

                    b.Navigation("Replay");
                });

            modelBuilder.Entity("ValidationRequestEntityValidationResultEntity", b =>
                {
                    b.HasOne("Revalidate.Entities.ValidationRequestEntity", null)
                        .WithMany()
                        .HasForeignKey("RequestsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Revalidate.Entities.ValidationResultEntity", null)
                        .WithMany()
                        .HasForeignKey("ResultsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Revalidate.Entities.ValidationLogEntity", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("Revalidate.Entities.ValidationResultEntity", b =>
                {
                    b.Navigation("Checkpoints");

                    b.Navigation("Distros");

                    b.Navigation("Inputs");
                });
#pragma warning restore 612, 618
        }
    }
}
