name: CI

on:
  push:
    branches: [ "main" ]
    paths: [ "Revalidate*/**" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "Revalidate*/**" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        cache: true
        cache-dependency-path: "**/packages.lock.json"
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
