name: CI

on:
  push:
    branches: [ "main" ]
    paths: [ "Revalidate*/**" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "Revalidate*/**" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
        
    - name: Restore dependencies
      run: dotnet restore Revalidate.slnx
      
    - name: Build
      run: dotnet build Revalidate.slnx --no-restore
      
    - name: Test
      run: dotnet test Revalidate.slnx --no-build --verbosity normal
